In [1]:
import numpy as np
import pandas as pd

In [3]:
# use numpy array() function to create numpy array
numpy_array = np.array([[1,2], [3,4]])
print(numpy_array)

[[1 2]
 [3 4]]


In [4]:
type(numpy_array)

numpy.ndarray

In [5]:
numpy_array.ndim

2

In [6]:
numpy_array.dtype

dtype('int64')

In [9]:
# if you create a numpy array with elements of different data types, numpy automatically upcasts the data type to a compatible data type that can accommodate all of them 
arr = np.array([[1, 2.5], [3.5,5]])
print(arr.dtype)

float64


In [10]:
# if you mix strings and numbers, numpy will upcast all elements to strings
arr = np.array([1, 'hello', 3.5])
print(arr.dtype)

<U32


In [11]:
import sys

# Create a NumPy array, Python list, and tuple with the same elements
array = np.arange(1000)
py_list = list(range(1000))
py_tuple = tuple(range(1000))

# Calculate memory usage
array_memory = array.nbytes
list_memory = sys.getsizeof(py_list) + sum(sys.getsizeof(item) for item in py_list)
tuple_memory = sys.getsizeof(py_tuple) + sum(sys.getsizeof(item) for item in py_tuple)

# Display the memory usage
memory_usage = {
    "NumPy Array (in bytes)": array_memory,
    "Python List (in bytes)": list_memory,
    "Python Tuple (in bytes)": tuple_memory
}

print(memory_usage)


# numpy arrays are memory efficient because they store elements of the same data type in contiguous memory locations

{'NumPy Array (in bytes)': 8000, 'Python List (in bytes)': 37108, 'Python Tuple (in bytes)': 36044}


In [12]:
#Examples showing NumPy arrays are more efficient for numerical computation
import time as tm
start_time = tm.time()
list_ex = list(range(1000000)) #List containinig whole numbers upto 1 million
a=(list_ex*2)
print("Time take to multiply numbers in a list = ", tm.time()-start_time)

start_time = tm.time()
tuple_ex = tuple(range(1000000)) #Tuple containinig whole numbers upto 1 million
a=(tuple_ex*2)
print("Time take to multiply numbers in a tuple = ", tm.time()-start_time)

start_time = tm.time()
numpy_ex = np.arange(1000000) #NumPy array containinig whole numbers upto 1 million
a=(numpy_ex*2)
print("Time take to multiply numbers in a NumPy array = ", tm.time()-start_time)



Time take to multiply numbers in a list =  0.030297040939331055
Time take to multiply numbers in a tuple =  0.028814077377319336
Time take to multiply numbers in a NumPy array =  0.0069010257720947266


In [13]:
numpy_ex = np.array([[1,2,3],[4,5,6]])
numpy_ex

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
numpy_ex.ndim

2

In [15]:
numpy_ex.shape

(2, 3)

In [16]:
numpy_ex.size

6

In [17]:
numpy_ex.dtype

dtype('int64')

In [19]:
# uses zero based indexing like lists
array = np.array([10, 20, 30, 40, 50])

# first element
print(array[0])  
# last element
print(array[4]) 
# last element
print(array[-1])  
# 3rd element when counting backwards
print(array[-3])  

10
50
50
30


In [20]:
# 2D array 3 rows 3 columns
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2d)
# first row second column
print(array_2d[0, 1])  
# 2nd row last column
print(array_2d[1, -1]) 
# last row last column
print(array_2d[-1, -1])  

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
6
9


In [24]:
array = np.array([10,20,30,40,50])
mask = array > 50 # boolean mask for elements > 50
print(array[mask])


[]


In [25]:
array = np.array([10, 20, 30, 40, 50])

# start:stop:step
# includes start excludes stop
print(array[1:4])  
print(array[:3])  
print(array[2:])  
print(array[::2])  
print(array[::-1]) 

[20 30 40]
[10 20 30]
[30 40 50]
[10 30 50]
[50 40 30 20 10]


In [26]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

#extract a sub array elements from the first two rows and first two columns
sub_array = array_2d[:2,:2]

# extract all rows for 2nd column
col = array_2d[:,1]

# Extract the last two rows and last two columns
sub_array = array_2d[-2:, -2:]
print(sub_array)  

[[5 6]
 [8 9]]


In [27]:
array = np.array([10, 20, 30, 40, 50])
array[1:4] = 100  # Replace elements from index 1 to 3 with 100
print(array)  # Output: [ 10 100 100 100  50]

[ 10 100 100 100  50]


In [28]:
# Create a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Select specific elements and slices
print(array_3d[0, :, 1])  # Output: [2 5] (second element from each row in the first sub-array)
print(array_3d[1, 1, :2])  # Output: [10 11] (first two elements in the last row of the second sub-array)

[2 5]
[10 11]


In [29]:
# Using np.where to create a mask and select elements greater than 5
greater_than_5 = np.where(array_3d > 5, array_3d, 0)
print("Elements greater than 5:\n", greater_than_5)

# Using np.select to categorize elements into three categories
conditions = [array_3d < 4, (array_3d >= 4) & (array_3d <= 8), array_3d > 8]
choices = ['low', 'medium', 'high']
categorized_array = np.select(conditions, choices, default='unknown')
print("\nCategorized array:\n", categorized_array)

Elements greater than 5:
 [[[ 0  0  0]
  [ 0  0  6]]

 [[ 7  8  9]
  [10 11 12]]]

Categorized array:
 [[['low' 'low' 'low']
  ['medium' 'medium' 'medium']]

 [['medium' 'medium' 'high']
  ['high' 'high' 'high']]]
